
sequenceDiagram
	actor Buyer
	actor Seller
	participant MD as Market Data Stream 
	participant P as Platform
	participant BE as Backend
	participant DB as Database
	participant SE as Settlement Engine (Order Book)
	participant R as Redis
	participant D as Dashboard
	
	MD -->> P: Price Snapshot
	P -->> Buyer: Show Current Price
	P -->> Seller: Show Current Price

	Buyer ->> P: Place Buy Order
	P ->> BE: Submit Buy Order
	BE ->> DB: Log the intent for transaction
	BE ->> DB: Record the transaction

	Seller ->> P: Place Sell Order
	P ->> BE: Submit Sell Order
	BE ->> DB: Log the intent for transaction
	BE ->> DB: Record the transaction
	
	BE ->> DB: Check holdings for Buyer/Seller
	DB -->> BE: Holdings Overview
	

	alt Insufficent funds or holdings
		rect rgb(255, 182, 193)
		Note over BE,DB: Rejection Path (Red)
		BE ->> DB: Update the status to insufficent assets
		BE ->> DB: Log the status
		BE --> P: Order Rejected
		
		alt Buyer lacks funds:
			P -->> Buyer: Notify insufficent funds
		else Seller lacks assets
			P -->> Seller: Notify insufficent assets
		end
		end
		
	else Sufficent funds/holdings
		rect rgb(144, 238, 144)
		Note over BE,SE: Approval Path (Green)
		BE ->> SE: Send orders to the order book
		Note over SE: Batch Processing, we process it at end of day
		
		alt Orders matched
			SE -->> BE: Match the buyer with seller
			BE ->> DB: Log the people who were a part of the transaction
			BE ->> DB: Update the status field for the transaction
			BE ->> DB: Log the overall transaction for it being matched
			SE -->> BE: Settlement Confirmed
			BE ->> DB: Update the holdings
			BE ->> DB: Change the status to complete
			BE ->> DB: Log the overall transaction for it being compeleted
			BE ->> R: Referesh Cache
			BE -->> P: Trade complete
			P -->> Buyer: Confirmation Message for oompletion
			P -->> Seller: Confirmation Message for completion
		else No match by 4pm
			rect rgb(255, 255, 153)
			Note over SE,BE: Expired Path (Yellow)
			SE -->> BE: Not executed
			BE ->> DB: Update the status to match failed
 			BE ->> DB: Log the transactionf as a match failed
			BE -->> P: Order expired
			P -->> Buyer: Notify the user that order didn't execute
			P -->> Seller: Notify the user that order didn't execute
			end
		end
		end
	end